---
apiVersion: batch/v1
kind: CronJob
metadata:
 name: cronjobpod
spec:
 schedule: "* * * * *"
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - image: ubuntu
           name: cronjobpod
           command: ["/bin/bash", "-c", "echo Jai Shree Ram; sleep 5"]
         restartPolicy: Never